spring:
  redis:
    host: localhost  # Redis servisine bağlanacak host (Docker-compose'da servis adıyla bağlanır)
    port: 6379   # Redis portu
    timeout: 60000  # İsteğe bağlı: Redis'e timeout süresi (milisaniye cinsinden)

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/  # Eureka sunucusuna bağlanma URL'si
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8084  # cartservice uygulamasının çalışacağı port

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Tüm yönetim endpointlerini açar (actuator gibi)

