server:
  port: 8081
spring:
  application:
    name: customerservice
  datasource:
    url: jdbc:mysql://mysql:3306/customer_db
    username: my_user
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      defaultBinder: kafka
      function:
        bindings:
          processOrderEvent-in-0: create-topic
      bindings:
        processOrderEvent-in-0:
          destination: create-topic
          content-type: application/json

      kafka:
        binder:
          brokers: kafka:9092
          consumerProperties:
            group.id: customer-service-group
      rabbit:
        binder:
          addresses: rabbit:5672
          username: guest
          password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
