server:
  port: 8081
spring:
  application:
    name: customerservice
  datasource:
    url: jdbc:mysql://mysql:3306/customer_db
    username: my_user
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      defaultBinder: kafka
      function:
        bindings:
          processCustomerCreatedEvent-out-0: create-topic
          customerUpdatedEvent-out-0: update-topic
          customerDeletedEvent-out-0: delete-topic
          bilAccntCreatedEvent-out-0: create-topic
          cncInfoUpdatedEvent-out-0: update-topic
      bindings:
        processCustomerCreatedEvent-out-0:
          destination: create-topic
          content-type: application/json
        customerUpdatedEvent-out-0:
          destination: update-topic
          content-type: application/json
        customerDeletedEvent-out-0:
          destination: delete-topic
          content-type: application/json
        bilAccntCreatedEvent-out-0:
          destination: create-topic
          content-type: application/json
        cncInfoUpdatedEvent-out-0:
          destination: update-topic
          content-type: application/json  
      kafka:
        binder:
          brokers: kafka:9092
      rabbit:
        binder:
          addresses: rabbit:5672
          username: guest
          password: guest
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
