spring:
  application:
    name: gateway
  cloud:
    gateway:
    #cors hatası deneme başlangıç
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      #cors hatası deneme biitş
      mvc:
        routes:
          - id: customer-service.routing
            uri: lb://customerservice # load-balancing
            predicates:
              - Path=/api/customers/**
          - id: cart-service.routing
            uri: lb://cartservice # load-balancing
            predicates:
              - Path=/api/carts/**

          - id: order-service.routing
            uri: lb://orderservice # load-balancing
            predicates:
              - Path=/api/orders/**
          - id: search-service.routing
            uri: lb://searchservice # load-balancing
            predicates:
              - Path=/api/search/**

          - id: identity-service.routing
            uri: lb://identityservice
            predicates:
              - Path=/api/v1/auth/**

          - id: catalog-service.routing
            uri: lb://catalogservice
            predicates:
              - Path=/api/catalogs/**

          - id: eureka.routing
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka.static-files
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/**  
server:
  port: 8090

eureka:
  url: http://eureka:8888
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
