spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identitydb
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
