spring:
  application:
    name: orderservice
  data:
    mongodb:
      uri: "mongodb://root:root@mongo:27017/orderdb?authSource=admin"
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
