spring:
  application:
    name: orderservice
  data:
    mongodb:
      database: orderdb
      uri: mongodb://localhost:27017
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
