spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"


