spring:
  application:
    name: searchservice
  data:
    mongodb:
      uri: "mongodb://root:root@mongo:27017/orderdb?authSource=admin"
  kafka:
    bootstrapServer: "localhost:9092"
    template:
      default-topic: orderTopic
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
