spring:
  cloud:
    stream:
      defaultBinder: kafka
      function:
        bindings:
          processCustomerCreatedEvent-in-0: create-topic
      bindings:
        processCustomerCreatedEvent-in-0:
          destination: create-topic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092
          consumerProperties:
            group.id: search-service-group
      rabbit:
        binder:
          addresses: rabbit:5672
          username: guest
          password: guest
  data:
    mongodb:
      uri: "mongodb://root:root@mongo:27017/searchdb?authSource=admin"
  application:
    name: searchservice
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
