spring:
  application:
    name: searchservice
  data:
    mongodb:
      uri: "mongodb://root:root@mongo:27017/searchdb?authSource=admin"
  
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
