spring:
  cloud:
    stream:
      defaultBinder: kafka
      function:
        bindings:
          processCustomerCreateEvent-in-0: create-topic
          processCustomerUpdatedEvent-in-0: update-topic
          processCustomerDeletedEvent-in-0: delete-topic
          processBilAccntCreatedEvent-in-0: create-topic
          processCncInfoUpdatedEvent-in-0: update-topic
      bindings:
        processCustomerCreateEvent-in-0:
          destination: create-topic
          content-type: application/json
        processCustomerUpdatedEvent-in-0:
          destination: update-topic
          content-type: application/json
        processCustomerDeletedEvent-in-0:
          destination: delete-topic
          content-type: application/json
        processBilAccntCreatedEvent-in-0:
          destination: create-topic
          content-type: application/json
        processCncInfoUpdatedEvent-in-0:
          destination: update-topic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092
          consumerProperties:
            group.id: group-id
      rabbit:
        binder:
          addresses: rabbitmq3:5672
          username: guest
          password: guest
  application:
    name: searchservice
  data:
    mongodb:
      uri: "mongodb://root:root@mongo:27017/searchdb?authSource=admin"
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
