spring:
  application:
    name: searchservice
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/searchdb?authSource=admin"
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.etiya.customerservice.kafka.events.customer'  # Sadece ilgili paketi güvenli olarak tanımlayın
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      specific-value-type: com.etiya.customerservice.kafka.events.customer.CustomerCreatedEvent  # Deserialization sınıfını açıkça belirtin
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
