spring:
  application:
    name: searchservice
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/searchdb?authSource=admin"
  kafka:
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      specific-value-type: org.example.searchservice.kafka.events.customer.CustomerCreatedEvent  # Deserialization sınıfını açıkça belirtin
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
